### ISSUE TITLE
Feature Vorschläge

### ISSUE THREAD

**Issue by Blue-EyesChaosMaxDragon** [timemir/squadapp#2]
Liste an Vorschlägen:
- Log-in für Squad Member
-  Simons (?) Cards against humanity squad edition implementieren (nur mit Log-in zugänglich)

**Comment by timemir** [comment]
Gute Idee, allerdings möchte ich erstmal keine User Auth, bzw. Accounts hinzufügen.  Ein Backend soll auch vorerst nicht implementiert werden, allerdings wird das sicherlich in naher Zukunft passieren.

Features, das mit dem letzten Update kam:
- Squad Autofill bei "Wer muss?"

Geplante Features:
-Random Drink Generator mit einer öffentlichen WebAPI

**Comment by timemir** [comment]
> Was genau ist mit der öffentlichen WebAPI beim RDG gemeint? Was soll das Feature am Ende machen?

Check out https://www.thecocktaildb.com/

Habe nun diese API in die SquadApp integriert. Nun brauchen wir neue Ideen 😄
